service: apollo-lambda
provider:
  name: aws
  runtime: nodejs16.x
  httpApi:
    cors: false
functions:
  graphql:
    handler: src/index.graphqlHandler # highlight-line
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET